:port: 8090
:debug: true

:subscribe_url: http://localhost:8080/socky/subscribe
:unsubscribe_url: http://localhost:8080/socky/unsubscribe

:secret: my_secret_key

:secure: false

# :timeout: 3

# :log_path: /var/log/socky.log
# :pid_path: /var/run/socky.pid

# :tls_options:
#   :private_key_file: /private/key
#   :cert_chain_file: /ssl/certificate
